const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/loaders/auth.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "API - Serviceasy",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    definitions: {
        
        AddUser: {
            $email: "laura@gideonsolutions.com.br",
            $password: 'Teste-123',
            $phone_number: "+5519993417478"
        },
        VerifyUser: {
            $email: "laura@gideonsolutions.com.br",
            $code:"XXXX"
        },
        LoginUser: {
            $email: "laurammoraes2@gmail.com",
            $password:"Ritinha-09"
        }
    }
    
    
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})