const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/routers/auth.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "API - Serviceasy",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints User"
        },
        {
            "name": "Auth",
            "description": "Endpoints Auth"
        },
        {
            "name": "Service",
            "description": "Endpoints Services"
        },
    ],
    definitions: {
        
        DataUser: {
            $email: "laurammoraes2@gmail.com",
            $password: 'Teste-123',
            $phoneNumber: "+5519993417478"
        },
        VerifyUser: {
            $email: "laurammoraes2@gmail.com",
            $codeEmailVerify:"XXXX"
        },
        LoginUser: {
            $email: "laurammoraes2@gmail.com",
            $password:"Ritinha-09"
        },
        ForgotPassword:{
            $email:"laurammoraes2@gmail.com",
        },
        UpdatePassword:{
            $email:"laurammoraes2@gmail.com", 
            $code:"733404", 
            $newPassword:"Laura-123"
        }, 
        UpdateUser:{
            $newPhoneNumber: "+5519993419999"
        },
        DataService:{
            $nameService: "Pintura de ambientes",
            $descService: "Realização da pintura de ambientes internos e externos",
            $priceMinService: "R$ 200,00",
            $productService: "Tinta e pincel",
            $avgTimeService: "50 minutos",
            $categoryService: "Pintura"



        },
    }
    
    
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})